name: Run Tests in PR
on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/build') }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.12.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.7
      - name: Install dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          echo requirements installed
      - name: Run tests
        working-directory: ./backend
        run: |
          python -m unittest test_api.py
